import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import Providers from "./providers";
import { NoSsr } from "@/components/noSsr";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NoSsr>
          <Providers>
            <Header />
            <Separator />
            <main className="p-8">{children}</main>
          </Providers>
        </NoSsr>
      </body>
    </html>
  );
}
