/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Faucet__factory } from "./ERC20Faucet__factory";
export { ZarC__factory } from "./ZarC__factory";
